In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('airbnb_nyc.csv')
df.head()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm

In [8]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
print(df)

       Unnamed: 0                  id  \
0               0            49849504
1               1            50891766
2               2            50699164
3               3            49871422
4               4            51245886
...           ...                 ...
12799       12799  640474109823176234
12800       12800            44697740
12801       12801            29975283
12803       12803             8006146
12804       12804            40547903

                                                    name rating reviews  \
0                                         Perla bungalov   4.71      64
1      Authentic Beach Architect Sheltered Villa with...    New       0
2                                      cottages sataplia   4.85      68
3                            Sapanca Breathable Bungalow    5.0      13
4                                          Bungalov Ev 2    New       0
...                                                  ...    ...     ...
12799                            Holiday home, Plemmirio    New       0
12800            Brown Dome House No. 3, full of healing   4.94      16
12801       Bubble Hotel Ubud with Bathtub under the Sky   4.67       6
12803     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86       7
12804   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85      13

             host_name      host_id  \
0            Mehmetcan  357334205.0
1                Fatih  386223873.0
2               Giorgi  409690853.0
3                Melih  401873242.0
4          Arp Sapanca  414884116.0
...                ...          ...
12799  Daphne Belvilla  385223440.0
12800            Aidan  161552316.0
12801           Martha  118954227.0
12803          Cempaka     718423.0
12804             Achy  246470880.0

                                                 address  \
0                               Kartepe, Kocaeli, Turkey
1                                   Kaş, Antalya, Turkey
2                                       Imereti, Georgia
3                               Sapanca, Sakarya, Turkey
4                               Sapanca, Sakarya, Turkey
...                                                  ...
12799                           Syracuse, Sicilia, Italy
12800  Imhoe-myeon, Jindo, South Jeolla Province, Sou...
12801                                 Gianyar, Indonesia
12803        Gunung Sari, Nusa Tenggara Barat, Indonesia
12804                              Uruma, Okinawa, Japan

                                        features  \
0           2 guests,2 bedrooms,1 bed,1 bathroom
1         4 guests,2 bedrooms,2 beds,2 bathrooms
2           4 guests,1 bedroom,3 beds,1 bathroom
3           4 guests,1 bedroom,2 beds,1 bathroom
4            2 guests,1 bedroom,1 bed,1 bathroom
...                                          ...
12799     8 guests,4 bedrooms,4 beds,2 bathrooms
12800                       4 guests,8 bathrooms
12801  2 guests,1 bedroom,1 bed,Toilet with sink
12803   8 guests,2 bedrooms,4 beds,2.5 bathrooms
12804       5 guests,1 bedroom,2 beds,1 bathroom

                                               amenities  ...  price  \
0      Mountain view,Valley view,Lake access,Kitchen,...  ...   8078
1      Kitchen,Wifi,Dedicated workspace,Free parking ...  ...   4665
2      Mountain view,Kitchen,Wifi,Dedicated workspace...  ...   5991
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...  ...  11339
4      Kitchen,Wifi,Free parking on premises,TV,Air c...  ...   6673
...                                                  ...  ...    ...
12799  Kitchen,Wifi,Dedicated workspace,Free on-stree...  ...  20311
12800  Kitchen,Wifi,Free parking on premises,Private ...  ...   4288
12801  Wifi,Free on-street parking,Air conditioning,G...  ...  15200
12803  Kitchen,Wifi,Dedicated workspace,Free parking ...  ...  42262
12804  Sea view,Beach access – Beachfront,Kitchen,Wif...  ...   9909

            country bathrooms  beds guests  toiles  bedrooms  studios  \
0            Turkey         1     1      2       0         2        0
1            Turkey         2     2      4       0         2        0
2           Georgia         1     3      4       0         1        0
3            Turkey         1     2      4       0         1        0
4            Turkey         1     1      2       0         1        0
...             ...       ...   ...    ...     ...       ...      ...
12799         Italy         2     4      8       0         4        0
12800   South Korea         8     0      4       0         0        0
12801     Indonesia         0     1      2       1         1        0
12803     Indonesia         2     4      8       0         2        0
12804         Japan         1     2      5       0         1        0

                   checkin   checkout
0                 Flexible   12 00 pm
1       4 00 pm - 11 00 pm   10 00 am
2            After 1 00 pm   12 00 pm
3            After 2 00 pm   12 00 pm
4            After 2 00 pm   12 00 pm
...                    ...        ...
12799    2 00 pm - 8 00 pm   10 00 am
12800   3 00 pm - 11 00 pm   11 00 am
12801   3 00 pm - 10 00 pm   12 00 pm
12803             Flexible   12 00 pm
12804        After 4 00 pm   11 00 am

[10189 rows x 23 columns]

SANITY CHECK : SHAPE , INFO

In [10]:
df.shape

(10189, 23)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10189 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    10189 non-null  int64
 1   id            10189 non-null  int64
 2   name          10189 non-null  object
 3   rating        10189 non-null  object
 4   reviews       10189 non-null  object
 5   host_name     10189 non-null  object
 6   host_id       10189 non-null  float64
 7   address       10189 non-null  object
 8   features      10189 non-null  object
 9   amenities     10189 non-null  object
 10  safety_rules  10189 non-null  object
 11  hourse_rules  10189 non-null  object
 12  img_links     10189 non-null  object
 13  price         10189 non-null  int64
 14  country       10189 non-null  object
 15  bathrooms     10189 non-null  int64
 16  beds          10189 non-null  int64
 17  guests        10189 non-null  int64
 18  toiles        10189 non-null  int64
 19  bedrooms      10189 non-null  int64
 20  studios       10189 non-null  int64
 21  checkin       10189 non-null  object
 22  checkout      10189 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 1.9+ MB

FINDING MISSING VALUES

In [12]:
df.isnull().sum()

Unnamed: 0      0
id              0
name            0
rating          0
reviews         0
host_name       0
host_id         0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
img_links       0
price           0
country         0
bathrooms       0
beds            0
guests          0
toiles          0
bedrooms        0
studios         0
checkin         0
checkout        0
dtype: int64

FINDING DUPLICATES

In [15]:
df.duplicated().sum()

0